version: "3.11"
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    volumes:
      - "./config.yaml:/app/config.yaml"
    command:
      - "--config=/app/config.yaml"
    ports:
      - "8080:4000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
      POSTGRES_DB: litellm
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
